accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('activate_user/<uuid:token>/', views.activate_user, name='activate_user'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),

    path('user_profile/<int:pk>', views.profile_detail, name='profile_detail'),
    path('user_profile/<int:pk>/edit', views.profile_edit, name='profile_edit'),
    path('user/<int:pk>/change_email', views.change_email, name='change_email'),
    path('user/<int:pk>/change_password', views.change_password, name='change_password'),
    path('user/<int:pk>/withdrawal', views.withdrawal, name='withdrawal'),

]

mylearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Profile
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password

User = get_user_model()

# ===== アカウント ===== #
class SignupForm(forms.ModelForm):

    confirm_password = forms.CharField(
        label='確認用パスワード',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = User
        fields = ('email', 'password', 'confirm_password')
        labels = {
            'email': 'メールアドレス',
            'password': 'パスワード'
        }
        widgets = {
            'email': forms.EmailInput(
                attrs={'class': 'form-control'}
            ),
            'password': forms.PasswordInput(
                attrs={'class':'form-control'}
            ),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('このメールアドレスは既に使用されています')
        return email

    def clean_password(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise ValidationError('パスワードが一致しません')
        return password

    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'])
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user


class LoginForm(forms.Form):
    email = forms.EmailField(
        label='メールアドレス',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    password = forms.CharField(
        label='パスワード',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )

# ===== プロフィール設定 ===== #
class ProfileForm(forms.ModelForm):
    username = forms.CharField(
        label='ユーザー名',
        widget=forms.TextInput(attrs={'class': 'form-control mb-3'})
    )

    class Meta:
        model = Profile
        fields = ('username', 'introduction', 'birth', 'thumbnail',)
        labels = {
            'introduction': '紹介文',
            'birth': '生年月日',
            'thumbnail': 'サムネイル画像'
        }
        widgets = {
            'introduction': forms.Textarea(attrs={
                'class': 'form-control mb-3',
                'rows': 6,
                'cols': 50
                }),
            'birth': forms.NumberInput(attrs={
                'class': 'form-control mb-3',
                'type': 'date'
                }),
            'thumbnail': forms.ClearableFileInput(attrs={
                'class': 'form-control mb-3',
                })

        }

# ===== メールアドレス設定 ===== #
class ChangeEmailForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email', 'password',)
        labels = {
            'email': 'メールアドレス',
            'password': 'パスワード',
        }
        widgets = {
            'email': forms.EmailInput(
                attrs={'class': 'form-control'}
            ),
            'password': forms.PasswordInput(
                attrs={'class':'form-control'}
            ),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('このメールアドレスは既に使用されています')
        return email


# ===== パスワード設定 ===== #
class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(
        required=True,
        label=' 現在のパスワード',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    new_password = forms.CharField(
        required=True,
        label='新しいパスワード',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        ),
    )
    confirm_password = forms.CharField(
        required=True,
        label='確認用パスワード',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        ),
    )

    def clean(self):
        cleaned_data = super().clean()
        print(cleaned_data)
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        print(f'new: {new_password}')
        print(f'confirm: {confirm_password}')

        if new_password and confirm_password and new_password != confirm_password:
            raise ValidationError('新しいパスワードが一致しません')
        return cleaned_data

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.core.exceptions import ValidationError
from django.contrib import messages
from .models import User, UserActivateToken, Profile
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.password_validation import validate_password
import json
from django.http import JsonResponse
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.http import JsonResponse
import random
import string


def index(request):
    return render(request, 'accounts/index.html')

# ===== アカウント ===== #

def signup(request):
    signup_form = forms.SignupForm(request.POST or None)
    if signup_form.is_valid():
        try:
            signup_form.save()
            messages.success(
                request, '認証メールを送信しましたので、ご確認ください')
            return redirect('accounts:index')
        except ValidationError as e:
            signup_form.add_error('password', e)
    return render(request, 'accounts/signup_form.html', context={
        'signup_form': signup_form,
    })


def activate_user(request, token):
    user_activate_token = UserActivateToken.objects.activate_user_by_token(token)

    if user_activate_token:
        messages.success(request, '認証が完了しました、ログインしてください')
        return render(request, 'accounts/index.html')
    else:
        messages.warning(request, 'トークンが有効ではありません、再度認証を実施してください')
        return render(request, 'accounts/index.html')


def user_login(request):
    login_form = forms.LoginForm(request.POST or None)

    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(
            email=email,
            password=password
        )

        if user:
            if user.is_active:
                login(request, user)
                messages.success(request, 'ログインが完了しました')
                return redirect('accounts:index')
            else:
                messages.warning(request, 'アカウント認証が完了していません')
        else:
            messages.warning(request, 'メールアドレスまたはパスワードが間違っています')
    return render(request, 'accounts/login_form.html', context={
            'login_form':login_form,
        })


@login_required
def user_logout(request):
    logout(request)
    messages.success(request, 'ログアウトしました')
    return redirect('accounts:index')


# ===== プロフィール ===== #
@login_required
def profile_detail(request, pk):
    profile = get_object_or_404(Profile, user_id=pk)
    user = profile.user
    return render(request, 'accounts/profile_detail.html', context={
        'profile': profile,
        'user': user,
    })


@login_required
def profile_edit(request, pk):
    profile_data = get_object_or_404(Profile, user_id=pk)
    if request.method == 'POST':
        profile_form = forms.ProfileForm(
            request.POST or None,
            request.FILES or None,
            instance=profile_data
        )
        if profile_form.is_valid():
            profile_instance = profile_form.save(commit=False)

            user_instance = profile_instance.user
            user_instance.username = profile_form.cleaned_data['username']
            user_instance.save()

            profile_instance.save()

            messages.success(request, 'プロフィールを更新しました')
            return redirect('accounts:profile_detail', pk=pk )
    else:
        profile_form = forms.ProfileForm(initial={
            'username': profile_data.user.username,
            'introduction': profile_data.introduction,
            'birth': profile_data.birth,
            'thumbnail': profile_data.thumbnail,
        })

    return render(request, 'accounts/profile_form.html', context={
        'profile_form': profile_form,
    })


# ===== メールアドレス ===== #
@login_required
def change_email(request, pk):
    user_data = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        change_email_form = forms.ChangeEmailForm(request.POST or None)
        if change_email_form.is_valid():
                email = change_email_form.cleaned_data.get('email')
                password = change_email_form.cleaned_data.get('password')
                user = authenticate(
                    email = user_data.email,
                    password = password
                )
                if user:
                    user_data.email = email
                    user_data.save()
                    messages.success(request, 'メールアドレスの変更が完了しました')
                    return redirect('accounts:change_email', pk=pk)
                else:
                    change_email_form.add_error('password', 'パスワードが間違っています')
    else:
        change_email_form = forms.ChangeEmailForm(initial={
            'email': user_data.email
        })

    return render(request, 'accounts/changeEmail_form.html', context={
        'change_email_form': change_email_form,
    })


# ===== パスワード ===== #
@login_required
def change_password(request, pk):
    user_data = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        change_password_form = forms.ChangePasswordForm(request.POST or None)
        if change_password_form.is_valid():
            try:
                new_password = change_password_form.cleaned_data['new_password']
                validate_password(new_password, user_data)
                current_password = change_password_form.cleaned_data.get('current_password')

                print(current_password)
                user = authenticate(
                    email=user_data.email,
                    password=current_password,
                )
                if user is not None:
                    user.set_password(new_password)
                    user.save()
                    login(request, user)
                    messages.success(request, 'パスワードの変更が完了しました')
                    return redirect('accounts:change_password', pk=pk)
                else:
                    change_password_form.add_error(None, 'パスワードが間違っています')
            except ValidationError as e:
                change_password_form.add_error('new_password', e)
    else:
        change_password_form = forms.ChangePasswordForm()
    return render(request, 'accounts/changePassword_form.html', context={
        'change_password_form': change_password_form,
    })


# ===== アカウント削除 ===== #
@login_required
def withdrawal(request, pk):
    user_data = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        try:
            # is_active = false
            user_data.is_active = False
            
            # メール通知
            subject = 'Notice of completion of withdrawal process'
            body = render_to_string(
                'accounts/mail_text/withdraw.txt',context={
                    'username': user_data.username,
                })

            from_email = ['admin@test.com']
            to = [user_data.email]

            email = EmailMessage(
                subject,
                body,
                from_email,
                to,
            )
            email.send()

            # email = musk
            new_email = generate_unique_email()
            user_data.email = new_email
            user_data.save()

            # ログアウト
            logout(request)
            messages.success(request, 'アカウント削除の手続きを完了致しました')
            return redirect('accounts:index')

        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    else:
        return render(request, 'accounts/withdrawal.html', context={
            'user_data': user_data,
        })


def generate_unique_email():
    random_string = ''.join(random.choices(string.ascii_letters + string.digits, k=35))
    email = f"{random_string}@{''.join(random.choices(string.ascii_letters + string.digits, k=10))}.com"

    while User.objects.filter(email=email).exists():
        random_string = ''.join(random.choices(string.ascii_letters + string.digits, k=35))
        email = f"{random_string}@{''.join(random.choices(string.ascii_letters + string.digits, k=10))}.com"

    return email

templates/accounts/changeEmail_form.html
{% extends 'base.html' %}

{% block title %}
メールアドレス変更
{% endblock %}

{% block content %}
<div class="w-25 border m-auto p-5">
    <h2 class="text-center mb-5">メールアドレス変更</h2>
    <form method='POST'>
        {% csrf_token %}
        {{ change_email_form.as_p }}
        <button type='submit' class='w-100 mt-3 btn btn-primary'>変更</button>
    </form>
</div>
{% endblock %}

templates/accounts/changePassword_form.html
{% extends 'base.html' %}

{% block title %}
パスワード変更
{% endblock %}

{% block content %}
<div class="w-25 border m-auto p-5">
    <h2 class="text-center mb-5">パスワード変更</h2>
    <form method='POST'>
        {% csrf_token %}
        {{ change_password_form.as_p }}
        <button type='submit' class='w-100 mt-3 btn btn-primary'>変更</button>
    </form>
</div>
{% endblock %}

templates/accounts/index.html
{% extends 'base.html' %}

{% block title %}
サンプルブログ
{% endblock %}



{% block content %}
TOPページ
{% endblock %}

templates/accounts/login_form.html
{% extends 'base.html' %}

{% block title %}
ログイン
{% endblock %}

{% block content %}
<div class="w-25 border m-auto p-5">
    <h2 class="text-center mb-5">ログイン</h2>
    <form method='POST'>
        {% csrf_token %}
        {{ login_form.as_p }}
        <button type='submit' class='w-100 mt-3 btn btn-primary'>ログイン</button>
    </form>
</div>
{% endblock %}
w

templates/accounts/profile_detail.html
{% extends 'base.html' %}

{% block title %}
プロフィール|詳細
{% endblock %}

{% block content %}
<h2 class="text-center">プロフィール情報</h2>

<div class="card mx-auto" style="width: 18rem;">
    {% if profile.thumbnail %}
    <img src="{{ profile.thumbnail.url }}" class="card-img-top" alt="サムネイル画像">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{ user.username }}</h5>
        <p class="card-text">birth: {{ profile.birth|date:"Y/m/d" }}  (age: {{ profile.age }})</p>
        <p class="card-text">
            intro: <br>
            {{ profile.introduction|linebreaksbr|wordwrap:25 }}
        </p>
        <p class="text-center"><a href="{% url 'accounts:profile_edit' user.pk %}" class="btn btn-primary">編集</a></p>
    </div>
</div>

{% endblock %}

templates/accounts/profile_form.html
{% extends 'base.html' %}

{% block title %}
プロフィール|変更
{% endblock %}

{% block content %}
<div class="w-25 border m-auto p-5">
    <h2 class="text-center mb-5">プロフィール変更</h2>
    <form method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {{ profile_form.username }}
        {{ profile_form.introduction }}
        {{ profile_form.birth }}
        {{ profile_form.thumbnail }}
        <button type='submit' class='w-100 mt-3 btn btn-primary'>更新</button>
    </form>
</div>
{% endblock %}

templates/accounts/signup_form.html
{% extends 'base.html' %}

{% block title %}
ユーザー登録
{% endblock %}

{% block content %}
<div class="w-25 border m-auto p-5">
    <h2 class="text-center mb-5">ユーザー登録</h2>
    <form method='POST'>
        {% csrf_token %}
        {{ signup_form.as_p }}
        <button type='submit' class='w-100 mt-3 btn btn-primary'>新規登録</button>
    </form>
</div>
{% endblock %}

templates/accounts/withdrawal.html
{% extends 'base.html' %}

{% block title %}
アカウント削除
{% endblock %}

{% block content %}

<div class="w-25 border m-auto p-5">
    <h2 class="text-center mb-5">アカウント削除</h2>
    <p>アカウントを削除すると、すべてのデータが削除されます。<br>
        ご注意ください。
    </p>
    <form action="" method="post">
        {% csrf_token %}
        <button id="confirmButton" class="btn btn-danger">アカウントを削除する</button>
    </form>
</div>

<script>
    function confirmButton() {
        confirm('本当に削除しますか？');
    }

    let btn = document.getElementById('confirmButton');
    btn.addEventListener('click', confirmButton);
</script>

{% endblock %}