accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('activate_user/<uuid:token>/', views.activate_user, name='activate_user'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),

    path('user_profile/<int:pk>', views.profile_detail, name='profile_detail'),
    path('user_profile/<int:pk>/edit', views.profile_edit, name='profile_edit'),
    path('user/<int:pk>/change_email', views.change_email, name='change_email'),
    path('user/<int:pk>/change_password', views.change_password, name='change_password'),
    path('user/<int:pk>/withdrawal', views.withdrawal, name='withdrawal'),

]

mylearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/flash_messages.html
{% if messages %}
{% for message in messages %}
    {% if message.tags == "success" %}
        <div class="alert alert-success text-center m-0 p-3">
            {{ message.message }}
        </div>
    {% elif message.tags == "warning" %}
        <div class="alert alert-danger text-center m-0 p-3">
            {{ message.message }}
        </div>
    {% endif %}
{% endfor %}
{% endif %}

templates/snippets/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'accounts:index' %}">タイトル</a>
        <ul class="navbar-nav ml-auto">


            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">投稿一覧</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">新規投稿</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    ユーザー設定
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'accounts:profile_detail' user.pk %}">プロフィール設定</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:change_email' user.pk %}">メールアドレス設定</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:change_password' user.pk %}">パスワード設定</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:withdrawal' user.pk %}">アカウント削除</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_logout' %}">ログアウト</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">ユーザー登録</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_login' %}">ログイン</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>